# This workflow will build a Java project with Maven
name: Java CI with Maven in Linux

on:
   push:
   pull_request:
  
jobs:
   build:
      runs-on: ubuntu-latest
      strategy:
         # test against several Java versions:
         # Additional-maven-args allow to active jacoco profile only for java 8
         matrix:
            include:
               - java: 8
                 additional-maven-args: >
                    -Pjacoco 
                    -DrepoToken=$COVERALLS_REPO_TOKEN
                    -DpullRequest=${{ github.event.pull_request.number }}
                    coveralls:report
               - java: 11

      name: Build with Java ${{ matrix.java }} on Linux
      steps:
      # Allow to import the repository on virtual environment
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
           java-version: ${{ matrix.java }}
      # Allow to import all .m2 directory, in this way we don't download all dependencies and plugins 
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
           path: ~/.m2
           key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
           restore-keys: ${{ runner.os }}-m2-
      # Using profile jacoco we can perform code coverage in the GitHub Actions workflow
      # Add environment variabile for sent coverage report to Coveralls from GitHub Actions workflow
      - name: Build with Maven
        run: >
          mvn -f exampleCI/pom.xml
          clean verify ${{ matrix.additional-maven-args }}
        env:
           COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      # Allow to generate JUnit Report even if we have a failure or error for one o more tests.
      - name: Generate JUnit Report
        run: >
          mvn -f exampleCI/pom.xml
          surefire-report:report-only site:site -DgenerateReports=false
        if: ${{ always() }}
      - name: Archive JUnit Report
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
         name: surefire-report-jdk-${{ matrix.java }}
         path: '**/target/site'

